plugin:
    name: 'offline.snipcartshop::lang.plugin.name'
    description: 'offline.snipcartshop::lang.plugin.description'
    author: 'OFFLINE GmbH'
    icon: oc-icon-shopping-cart
    homepage: ''
navigation:
    snipcart-shop:
        label: 'offline.snipcartshop::lang.plugin.common.shop'
        url: offline/snipcartshop/products
        icon: icon-shopping-cart
        sideMenu:
            snipcartshop-products:
                label: 'offline.snipcartshop::lang.plugin.common.products'
                url: offline/snipcartshop/products
                icon: icon-cart-plus
            snipcartshop-categories:
                label: 'offline.snipcartshop::lang.plugin.common.categories'
                url: offline/snipcartshop/categories
                icon: icon-sitemap
            snipcartshop-orders:
                label: 'offline.snipcartshop::lang.plugin.common.orders'
                url: offline/snipcartshop/orders
                icon: icon-check-circle
            snipcartshop-discounts:
                label: 'offline.snipcartshop::lang.plugin.common.discounts'
                url: offline/snipcartshop/discounts
                icon: icon-gift
