title: 'offline.snipcartshop::lang.plugin.common.products'
modelClass: OFFLINE\SnipcartShop\Models\Product
list: $/offline/snipcartshop/models/product/columns.yaml
recordUrl: 'offline/snipcartshop/products/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
showSorting: 1
defaultSort:
    column: name
    direction: asc
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'

filter: config_filter.yaml
