title: 'offline.snipcartshop::lang.plugin.common.discounts'
modelClass: OFFLINE\SnipcartShop\Models\Discount
list: $/offline/snipcartshop/models/discount/columns.yaml
recordUrl: 'offline/snipcartshop/discounts/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
showSorting: 1
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
